<?php

namespace DoctrineExtensions\Tree\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TreeFixtureBehavioralCategoryProxy extends \Tree\Fixture\BehavioralCategory implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getSlug()
    {
        $this->_load();
        return parent::getSlug();
    }

    public function setTitle($title)
    {
        $this->_load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->_load();
        return parent::getTitle();
    }

    public function setParent(\Tree\Fixture\BehavioralCategory $parent)
    {
        $this->_load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function getTreeConfiguration()
    {
        $this->_load();
        return parent::getTreeConfiguration();
    }

    public function getSluggableConfiguration()
    {
        $this->_load();
        return parent::getSluggableConfiguration();
    }

    public function getTranslatableFields()
    {
        $this->_load();
        return parent::getTranslatableFields();
    }

    public function getTranslatableLocale()
    {
        $this->_load();
        return parent::getTranslatableLocale();
    }

    public function getTranslationEntity()
    {
        $this->_load();
        return parent::getTranslationEntity();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'lft', 'rgt', 'parent', 'children', 'slug');
    }
}