<?php

namespace Gedmo\Tree\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TreeFixtureUserGroupProxy extends \Tree\Fixture\UserGroup implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getRoleId()
    {
        $this->_load();
        return parent::getRoleId();
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function setParent(\Tree\Fixture\UserGroup $parent)
    {
        $this->_load();
        return parent::setParent($parent);
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getLeft()
    {
        $this->_load();
        return parent::getLeft();
    }

    public function getRight()
    {
        $this->_load();
        return parent::getRight();
    }

    public function getLevel()
    {
        $this->_load();
        return parent::getLevel();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'parent', 'children', 'lft', 'rgt', 'lvl', 'role', 'name');
    }
}