name: Stale

on:
  schedule:
    - cron: 0 9-18 * * *

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues and pull requests
        uses: actions/stale@v9
        with:
          days-before-close: 30
          days-before-stale: 180
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: 'Still Relevant'
          stale-issue-label: 'Stale'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          stale-pr-label: 'Stale'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
